from setuptools import setup, find_packages

setup(
    name="peft_project",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.36.0",
        "datasets>=2.18.0",
        "peft>=0.5.0",
        "scikit-learn>=1.6.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "pandas>=2.0.0",
        "numpy>=1.25.0",
        "jupyter>=1.0.0",
        "bitsandbytes>=0.38.0",
        "tqdm>=4.66.0",
        "ipywidgets>=8.0.0",
    ],
    author="PEFT Project Team",
    author_email="your.email@example.com",
    description="Parameter-Efficient Fine-Tuning for NLP Models",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    keywords="nlp, peft, lora, fine-tuning, parameter-efficient, transformers",
    url="https://github.com/username/parameter-efficient-fine-tuning",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
)
